### ISSUE TITLE
Suggestion: Organization by Continent Folders for Readability

### ISSUE THREAD

**Issue by geraldb** [glean/countries#2]
Hello, great initiative. FYI: You might consider organizing countries by continent folders (such as North America, Caribbean, Europe, Middle East, etc.  You can see a working real  world example in my very own world.db countries dataset [github.com/openmundi/world.db](https://github.com/openmundi/world.db)   Keep it up. Cheers.

**Comment by johndbritton** [comment]
Thanks for the idea @geraldb. Currently the directory structure has no effect on the actual dataset, so the organization is purely for humans browsing the raw files. I'm more focused on improving Glean itself right now than the individual datasets, but I agree this would be an improvement.
